variables:
    GIT_STRATEGY: clone

stages:
    - test

before_script:
    - git submodule sync --recursive
    - git submodule update --init --recursive

ClangFormatCheck:
  stage: test
  image: bce7edfda510
  script:
  - ./.github/automation/clang-format.sh

gcc:
  stage: test
  image: bce7edfda510
  script:
    - source .github/automation/env/setenv-gcc
    - make
    - cd test
    - ./test_all.sh
fcc:
  stage: test
  image: bce7edfda510
  script:
    - source .github/automation/env/setenv-fcc
    - make
    - cd test
    - ./test_all.sh
